# Generated by Django 5.2.4 on 2025-08-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='mpesa_request_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='M-Pesa request ID'),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='transaction ID'),
        ),
    ]
