# Generated by Django 5.2.5 on 2025-08-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_mpesa_request_id_payment_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='KSH', max_length=3, verbose_name='currency'),
        ),
    ]
