# Generated by Django 5.2.4 on 2025-07-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_verification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='verification token'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_token_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='verification token created at'),
        ),
    ]
