# Generated by Django 5.2.4 on 2025-08-04 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_verification_token_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="verification_token",
        ),
        migrations.RemoveField(
            model_name="user",
            name="verification_token_created_at",
        ),
    ]
